import { useState } from 'react'
import { api, type Settings } from '../lib/api'
import { Card, PageHeader } from './Shell'

type CliSettings={baseUrl?:string;apiKey?:string;model?:string;subagentModel?:string;reasoningEffort?:string}
export function ApiView({settings,cliStatus,models}:{settings:Settings|null;cliStatus:Record<string,unknown>|null;models:string[]}){
 const endpoint=`http://${settings?.host==='0.0.0.0'?'127.0.0.1':settings?.host||'127.0.0.1'}:${settings?.port||8080}/v1`;const tools=normaliseTools(cliStatus)
 const [tool,setTool]=useState('');const [form,setForm]=useState<CliSettings>({});const [busy,setBusy]=useState(false);const [message,setMessage]=useState('')
 const open=async(name:string)=>{setBusy(true);setMessage('');try{const current=await api.cliToolSettings(name);setForm({...current,apiKey:''});setTool(name)}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
 const apply=async()=>{setBusy(true);setMessage('');try{const payload:Record<string,unknown>={baseUrl:form.baseUrl||endpoint,model:form.model||'',reasoningEffort:form.reasoningEffort||'high'};if(form.subagentModel)payload.subagentModel=form.subagentModel;if(form.apiKey)payload.apiKey=form.apiKey;await api.applyCliTool(tool,payload);setMessage('Đã áp dụng cấu hình CLI.')}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
 const test=async()=>{if(!form.model)return;setBusy(true);setMessage('');try{const result=await api.testModel(form.model);setMessage((result as {ok?:boolean;error?:string}).ok?'Model hoạt động.':(result as {error?:string}).error||'Kiểm thử thất bại.')}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy(false)}}
 return <div className="mx-auto max-w-7xl"><PageHeader title="API & CLI" description="Kiểm tra endpoint, model công khai và cấu hình công cụ trực tiếp, không cần quay về UI cũ."/>{message&&<div role="status" className="mb-4 rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
 <div className="grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Card className="p-5"><h2 className="font-semibold">Kết nối API</h2><dl className="mt-4 space-y-3"><KV k="Base URL" v={endpoint} mono/><KV k="Xác thực" v={settings?.requireApiKey?'Bắt buộc API key':'Không bắt buộc'}/><KV k="API key" v={settings?.apiKey?'Đã cấu hình · được che':'Chưa cấu hình'}/><KV k="Model" v={`${models.length} model khả dụng`}/></dl><button className="btn mt-5 w-full" onClick={()=>void navigator.clipboard.writeText(endpoint)}>Sao chép Base URL</button></Card>
 <Card className="overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Trạng thái CLI</h2><p className="mt-1 text-xs text-slate-500">Mở từng công cụ để đọc cấu hình hiện tại trước khi ghi.</p></div><div className="grid gap-px bg-slate-100 sm:grid-cols-2">{tools.length?tools.map(([name,value])=><button className="flex items-center justify-between bg-white px-5 py-4 text-left hover:bg-slate-50" key={name} disabled={busy} onClick={()=>void open(name)} aria-label={`Cấu hình ${labelTool(name)}`}><span className="text-sm font-medium">{labelTool(name)}</span><span className={`rounded-full px-2 py-1 text-[11px] ${truthyStatus(value)?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{statusLabel(value)}</span></button>):<div className="bg-white p-8 text-center text-sm text-slate-500 sm:col-span-2">Chưa nhận được trạng thái CLI.</div>}</div></Card></div>
 {tool&&<Card className="mt-5 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Cấu hình {labelTool(tool)}</h2><button className="btn" onClick={()=>setTool('')}>Đóng</button></div><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm">Base URL<input className="input mt-1 w-full" value={form.baseUrl||endpoint} onChange={e=>setForm({...form,baseUrl:e.target.value})}/></label><label className="text-sm">Model CLI<input aria-label="Model CLI" className="input mt-1 w-full" list="public-models" value={form.model||''} onChange={e=>setForm({...form,model:e.target.value})}/><datalist id="public-models">{models.map(m=><option value={m} key={m}/>)}</datalist></label><label className="text-sm">Reasoning effort<select className="input mt-1 w-full" value={form.reasoningEffort||'high'} onChange={e=>setForm({...form,reasoningEffort:e.target.value})}><option value="low">low</option><option value="medium">medium</option><option value="high">high</option></select></label><label className="text-sm">API key mới (để trống nếu không đổi)<input type="password" autoComplete="new-password" className="input mt-1 w-full" value={form.apiKey||''} onChange={e=>setForm({...form,apiKey:e.target.value})}/></label></div><div className="mt-5 flex gap-2"><button className="btn" disabled={busy||!form.model} onClick={()=>void test()}>Kiểm thử model</button><button className="btn-primary" disabled={busy} onClick={()=>void apply()}>Áp dụng cấu hình</button></div></Card>}
 <Card className="mt-5 overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Model công khai</h2><p className="mt-1 text-xs text-slate-500">Catalog đang được `/v1/models` công bố.</p></div><div className="grid gap-px bg-slate-100 sm:grid-cols-2 lg:grid-cols-3">{models.map(m=><div className="truncate bg-white px-4 py-3 font-mono text-xs" title={m} key={m}>{m}</div>)}</div></Card></div>
}
function normaliseTools(v:Record<string,unknown>|null):Array<[string,unknown]>{if(!v)return[];const source=(v.tools&&typeof v.tools==='object'?v.tools:v) as Record<string,unknown>;return Object.entries(source).filter(([k])=>!['success','error'].includes(k)).slice(0,24)}
function truthyStatus(v:unknown){if(typeof v==='boolean')return v;if(typeof v==='string')return ['true','configured','active','running','installed'].includes(v.toLowerCase());if(v&&typeof v==='object'){const o=v as Record<string,unknown>;return Boolean(o.hasOmniProxy||o.configured||o.active||o.running||o.installed)}return false}
function statusLabel(v:unknown){if(typeof v==='string')return v;if(typeof v==='boolean')return v?'Đã cấu hình':'Chưa cấu hình';return truthyStatus(v)?'Đã cấu hình':'Chưa cấu hình'}
function labelTool(s:string){return s.replace(/[-_]/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function KV({k,v,mono=false}:{k:string;v:string;mono?:boolean}){return <div className="grid grid-cols-[90px_1fr] gap-3 text-sm"><dt className="text-slate-500">{k}</dt><dd className={`min-w-0 break-all text-right font-medium ${mono?'font-mono text-xs':''}`}>{v}</dd></div>}
