import { useEffect, useMemo, useRef, useState } from 'react'
import { getToken } from '../lib/api'
import { Card, PageHeader } from './Shell'

export function LogsView({initialLines=[]}:{initialLines?:string[]}){
 const [lines,setLines]=useState(()=>initialLines.slice(-1000));const [query,setQuery]=useState('');const [level,setLevel]=useState('all');const [paused,setPaused]=useState(false);const [status,setStatus]=useState('Đang kết nối');const cursor=useRef('');const source=useRef<EventSource|null>(null);const pausedRef=useRef(false)
 const connect=()=>{source.current?.close();const params=new URLSearchParams({tail:'1000'});const token=getToken();if(token)params.set('token',token);if(cursor.current)params.set('lastEventId',cursor.current);const next=new EventSource(`/admin/api/logs/stream?${params}`);source.current=next;next.onopen=()=>setStatus('Đang theo dõi');next.onmessage=event=>{if(event.lastEventId)cursor.current=event.lastEventId;if(pausedRef.current)return;try{const data=JSON.parse(event.data) as {line?:string};if(data.line)setLines(current=>[...current,data.line!].slice(-1000))}catch{if(event.data)setLines(current=>[...current,event.data].slice(-1000))}};next.onerror=()=>setStatus('Đang kết nối lại')}
 useEffect(()=>{connect();return()=>source.current?.close()},[])
 const toggle=()=>{if(!paused){pausedRef.current=true;setPaused(true);source.current?.close();setStatus('Đã tạm dừng')}else{pausedRef.current=false;setPaused(false);setStatus('Đang kết nối');connect()}}
 const shown=useMemo(()=>lines.filter(l=>(!query||l.toLowerCase().includes(query.toLowerCase()))&&(level==='all'||l.toLowerCase().includes(level))).slice(-1000),[lines,query,level])
 return <div className="mx-auto flex max-w-7xl flex-col"><PageHeader title="Nhật ký" description="Live tail qua SSE có cursor tiếp tục; trình xem chỉ giữ tối đa 1.000 dòng gần nhất." action={<span className="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">{status}</span>}/><div className="mb-3 flex flex-wrap gap-2"><input className="input min-w-64 flex-1" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm model, account, mã lỗi…"/><select className="input" value={level} onChange={e=>setLevel(e.target.value)}><option value="all">Mọi mức</option><option value="error">Error</option><option value="warn">Warning</option><option value="info">Info</option></select><button className="btn" onClick={toggle}>{paused?'Tiếp tục':'Tạm dừng'}</button><button className="btn" onClick={()=>setLines([])}>Xóa màn hình</button><span className="self-center font-mono text-xs text-slate-500">{shown.length}/{lines.length} dòng</span></div><Card className="overflow-hidden bg-[#0b1220]"><div className="max-h-[calc(100dvh-220px)] min-h-[520px] overflow-auto p-4 font-mono text-[11px] leading-5 text-slate-300">{shown.length?shown.map((l,i)=><div className={`${tone(l)} whitespace-pre-wrap break-all border-b border-white/5 py-0.5`} key={`${i}-${l.slice(0,24)}`}>{l}</div>):<div className="grid min-h-96 place-items-center text-slate-500">Không có dòng log phù hợp.</div>}</div></Card></div>
}
function tone(l:string){const s=l.toLowerCase();return s.includes('error')||s.includes('fatal')?'text-red-300':s.includes('warn')?'text-amber-300':s.includes('success')?'text-emerald-300':''}
