import { useState } from 'react'
import { api, type QuotaOverview } from '../lib/api'
import { Card, PageHeader } from './Shell'
import { accountLabel } from '../lib/format'

export function QuotaView({data,onReload}:{data:QuotaOverview|null;onReload?:()=>void|Promise<void>}){
 const [busy,setBusy]=useState('');const [message,setMessage]=useState('')
 const act=async(id:string,kind:'refresh'|'credits'|'reset')=>{setBusy(`${kind}:${id}`);setMessage('');try{if(kind==='refresh')await api.refreshAccount(id);else if(kind==='credits')await api.refreshCredits(id);else{const available=await api.resetCreditsAvailable(id);if(!available.available){setMessage('Tài khoản không còn lượt bank reset.');return}if(!window.confirm(`Dùng 1 trong ${available.available} lượt bank reset?`))return;await api.resetCredits(id)}await onReload?.();setMessage('Đã cập nhật hạn mức.')}catch(error){setMessage(error instanceof Error?error.message:String(error))}finally{setBusy('')}}
 const providers=Object.values(data?.providers||{}).filter(p=>p.accounts>0)
 return <div className="mx-auto max-w-7xl"><PageHeader title="Hạn mức" description="Ưu tiên phần còn lại và thời điểm reset; có thể làm mới trực tiếp theo từng tài khoản."/>
 {message&&<div role="status" className="mb-4 rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{providers.map(p=><Card className="p-5" key={p.provider}><div className="text-sm font-semibold">{p.label}</div><div className="mt-1 text-xs text-slate-500">{p.activeAccounts}/{p.accounts} tài khoản hoạt động</div>{p.usageLimit>0?<Bar remaining={Math.max(0,100-p.usagePercent)} label={`${Math.max(0,100-p.usagePercent).toFixed(0)}% còn lại`}/>:<div className="mt-4 text-xs text-slate-500">Không có quota tổng hợp</div>}</Card>)}</div>
 <div className="mt-5 grid gap-4 lg:grid-cols-2">{(data?.accounts||[]).slice().sort((a,b)=>minRemaining(a)-minRemaining(b)).map(a=><Card className="p-5" key={a.id}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate text-sm font-semibold">{accountLabel(a as never)}</h2><p className="mt-1 text-xs text-slate-500">{a.providerLabel||a.provider}</p></div><span className={`rounded-full px-2 py-1 text-[11px] ${a.enabled?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{a.status||a.banStatus||(a.enabled?'Đang bật':'Đã tắt')}</span></div><div className="mt-4 space-y-4">{a.quotas?.length?a.quotas.map((q,i)=><div key={`${q.name}-${i}`}><div className="mb-1 flex justify-between text-xs"><span>{q.name}</span><span className="font-mono tabular-nums">{quotaValue(q)}{q.resetAt?` · reset ${new Date(q.resetAt*1000).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}`:''}</span></div>{q.total>0?<Bar remaining={q.remaining}/>:<div className="h-1.5 rounded-full bg-slate-100"/>}</div>):<div className="text-xs text-slate-500">Chưa có quota từ upstream.</div>}</div><div className="mt-5 flex flex-wrap gap-2"><button className="btn" disabled={Boolean(busy)} onClick={()=>void act(a.id,'refresh')}>{busy===`refresh:${a.id}`?'Đang làm mới…':'Làm mới'}</button>{a.provider==='external'&&<button className="btn" disabled={Boolean(busy)} onClick={()=>void act(a.id,'credits')}>Kiểm tra credit</button>}{a.provider==='codex'&&<button className="btn" disabled={Boolean(busy)} onClick={()=>void act(a.id,'reset')}>Bank reset</button>}</div></Card>)}</div></div>
}
function minRemaining(a:QuotaOverview['accounts'][number]){const q=a.quotas?.filter(x=>x.total>0)||[];return q.length?Math.min(...q.map(x=>x.remaining)):101}
function quotaValue(q:QuotaOverview['accounts'][number]['quotas'] extends Array<infer T>|undefined?T:never){return q.total>0?`${q.remaining}% còn`:q.unit==='∞'?'Không giới hạn':`${new Intl.NumberFormat('vi-VN').format(q.used)} ${q.unit||''}`}
function Bar({remaining,label}:{remaining:number;label?:string}){const c=remaining<=10?'bg-red-500':remaining<=30?'bg-amber-500':'bg-emerald-500';return <div className="mt-4"><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${c}`} style={{width:`${Math.max(1,Math.min(100,remaining))}%`}}/></div>{label&&<div className="mt-1 text-right font-mono text-[11px] text-slate-500">{label}</div>}</div>}
