import { useEffect, useState } from 'react'
import { api, type Settings } from '../lib/api'
import { Card, PageHeader } from './Shell'

type Endpoint={preferredEndpoint:string;endpointFallback:boolean}
export function SettingsView({settings,onReload}:{settings:Settings|null;onReload?:()=>void|Promise<void>}){
 const [endpoint,setEndpoint]=useState<Endpoint>({preferredEndpoint:'auto',endpointFallback:true});const [proxy,setProxy]=useState('');const [allow,setAllow]=useState(Boolean(settings?.allowOverUsage));const [requireKey,setRequireKey]=useState(settings?.requireApiKey??true);const [newKey,setNewKey]=useState('');const [message,setMessage]=useState('')
 useEffect(()=>{let live=true;Promise.all([api.endpoint(),api.proxy()]).then(([e,p])=>{if(live){setEndpoint(e);setProxy(p.proxyURL||'')}}).catch(e=>{if(live)setMessage(e instanceof Error?e.message:String(e))});return()=>{live=false}},[])
 const saveNetwork=async()=>{if(!window.confirm('Áp dụng thay đổi routing và forward proxy ngay?'))return;setMessage('');try{await api.updateEndpoint(endpoint);await api.updateProxy(proxy.trim());await onReload?.();setMessage('Đã lưu routing và proxy.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 const saveSecurity=async()=>{setMessage('');try{const payload:{requireApiKey:boolean;allowOverUsage:boolean;apiKey?:string}={requireApiKey:requireKey,allowOverUsage:allow};if(newKey.trim())payload.apiKey=newKey.trim();await api.updateSettings(payload);setNewKey('');await onReload?.();setMessage('Đã lưu thiết lập bảo mật.')}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
 return <div className="mx-auto max-w-5xl"><PageHeader title="Thiết lập" description="Chỉnh routing, proxy và bảo vệ API trực tiếp. Mọi thay đổi nhạy cảm đều có phạm vi rõ ràng."/>{message&&<div role="status" className="mb-4 rounded-lg border border-slate-200 bg-white px-4 py-3 text-sm">{message}</div>}
 <div className="grid gap-4 md:grid-cols-2"><Card className="p-5"><h2 className="font-semibold">Routing và proxy</h2><div className="mt-4 space-y-4"><label className="block text-sm">Upstream ưu tiên<select aria-label="Upstream ưu tiên" className="input mt-1 w-full" value={endpoint.preferredEndpoint} onChange={e=>setEndpoint({...endpoint,preferredEndpoint:e.target.value})}><option value="auto">auto</option><option value="kiro">kiro</option><option value="codewhisperer">codewhisperer</option><option value="amazonq">amazonq</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={endpoint.endpointFallback} onChange={e=>setEndpoint({...endpoint,endpointFallback:e.target.checked})}/>Cho phép endpoint fallback</label><label className="block text-sm">Forward proxy<input aria-label="Forward proxy" className="input mt-1 w-full" placeholder="socks5://127.0.0.1:1080" value={proxy} onChange={e=>setProxy(e.target.value)}/></label><button className="btn-primary" onClick={()=>void saveNetwork()}>Lưu routing và proxy</button></div></Card>
 <Card className="p-5"><h2 className="font-semibold">Bảo vệ API</h2><div className="mt-4 space-y-4"><div className="text-sm text-slate-600">API key hiện tại: {settings?.apiKey?'đã cấu hình và không hiển thị':'chưa cấu hình'}</div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={requireKey} onChange={e=>setRequireKey(e.target.checked)}/>Bắt buộc API key</label><label className="flex items-center gap-2 text-sm"><input aria-label="Cho phép vượt quota" type="checkbox" checked={allow} onChange={e=>setAllow(e.target.checked)}/>Cho phép vượt quota</label><label className="block text-sm">API key mới (để trống nếu không đổi)<input type="password" autoComplete="new-password" className="input mt-1 w-full" value={newKey} onChange={e=>setNewKey(e.target.value)}/></label><button className="btn-primary" onClick={()=>void saveSecurity()}>Lưu bảo mật</button></div></Card></div>
 <Card className="mt-5 border-amber-200 bg-amber-50/50 p-5"><h2 className="text-sm font-semibold text-amber-900">Ranh giới an toàn</h2><p className="mt-1 text-xs leading-5 text-amber-800">Màn hình này không restart dịch vụ, reset thống kê hoặc đổi mật khẩu quản trị. Routing và proxy được backend áp dụng ngay sau xác nhận.</p></Card></div>
}
