import { useMemo } from 'react'
import type { ChartPoint, UsageStats } from '../lib/api'
import { compactNumber, exactNumber } from '../lib/format'
import { Card, PageHeader } from './Shell'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'

export function UsageView({usage,chart,period,onPeriod}:{usage:UsageStats|null;chart:ChartPoint[];period:string;onPeriod:(p:string)=>void}){
 const models=useMemo(()=>Object.entries(usage?.byModel||{}).sort((a,b)=>b[1].requests-a[1].requests).slice(0,12),[usage])
 return <div className="mx-auto max-w-7xl"><PageHeader title="Sử dụng" description="Lưu lượng, token và chi phí theo cùng một khoảng thời gian; bảng chi tiết chỉ giữ các chiều có giá trị quyết định." action={<select className="input" value={period} onChange={e=>onPeriod(e.target.value)}><option value="1h">1 giờ</option><option value="24h">24 giờ</option><option value="7d">7 ngày</option><option value="30d">30 ngày</option></select>}/>
 <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric l="Request" v={compactNumber(usage?.totalRequests)}/><Metric l="Input token" v={compactNumber(usage?.totalPromptTokens)}/><Metric l="Output token" v={compactNumber(usage?.totalCompletionTokens)}/><Metric l="Chi phí ước tính" v={`$${(usage?.totalRealCost??usage?.totalCost??0).toFixed(3)}`}/></div>
 <div className="mt-5 grid gap-5 xl:grid-cols-[1.4fr_.6fr]"><Card className="p-5"><h2 className="font-semibold">Xu hướng token</h2><p className="mb-5 text-xs text-slate-500">Theo bucket của server</p><div className="h-72">{chart.length?<ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id="usage-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#2563eb" stopOpacity={.28}/><stop offset="100%" stopColor="#2563eb" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="label" tick={{fontSize:11}} minTickGap={28}/><YAxis tickFormatter={compactNumber} tick={{fontSize:11}} width={48}/><Tooltip formatter={(v)=>[exactNumber(Number(v)),'Token']}/><Area type="monotone" dataKey="tokens" stroke="#2563eb" fill="url(#usage-fill)" strokeWidth={2}/></AreaChart></ResponsiveContainer>:<Empty/>}</div></Card><Card><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Request đang chạy</h2></div><div className="divide-y divide-slate-100">{usage?.activeRequests?.length?usage.activeRequests.map((r,i)=><div className="p-4 text-xs" key={`${r.accountId}-${i}`}><div className="font-mono font-medium">{r.model}</div><div className="mt-1 text-slate-500">{r.provider} · {r.accountId.slice(0,8)}</div></div>):<Empty/>}</div></Card></div>
 <Card className="mt-5 overflow-hidden"><div className="border-b border-slate-200 p-5"><h2 className="font-semibold">Model theo lưu lượng</h2></div><table className="data-table"><thead><tr><th>Model</th><th className="num">Request</th><th className="num">Input</th><th className="num">Output</th><th className="num">Chi phí</th></tr></thead><tbody>{models.map(([name,s])=><tr key={name}><td className="font-mono text-xs">{name}</td><td className="num">{exactNumber(s.requests)}</td><td className="num">{compactNumber(s.promptTokens)}</td><td className="num">{compactNumber(s.completionTokens)}</td><td className="num">${(s.realCost??s.cost??0).toFixed(3)}</td></tr>)}</tbody></table>{!models.length&&<Empty/>}</Card>
 <p className="mt-4 text-right"><a className="text-xs font-medium text-blue-700 hover:underline" href="/admin/#usage">Request details, cache và compression trong UI cũ ↗</a></p></div>}
function Metric({l,v}:{l:string;v:string}){return <Card className="p-5"><div className="text-xs font-medium uppercase tracking-wide text-slate-500">{l}</div><div className="mt-2 font-mono text-2xl font-semibold tabular-nums">{v}</div></Card>}
function Empty(){return <div className="p-8 text-center text-sm text-slate-500">Chưa có dữ liệu trong kỳ.</div>}
